name: FroggySpigot
version: 1.0.0
author: evilFrog
main: com.evilfrogindustries.froggyspigot.FroggySpigot
commands:
  frogkit:
    description: Lilypads
    usage: /frogkit
  cgkit:
    description: Items given by config file.
    usage: /configkit
  getalchstone:
    description: Gives you an alchemy stone.
    usage: /configkit